alter table "lead_journeys" add column "first_visit_id" integer;
alter table "lead_journeys" add column "first_campaign_id" integer;
alter table "lead_journeys" add column "first_page_id" integer;
alter table "lead_journeys" add column "first_utm_source" text;
alter table "lead_journeys" add column "first_utm_medium" text;
alter table "lead_journeys" add column "first_utm_campaign" text;
alter table "lead_journeys" add column "first_referrer" text;
alter table "lead_journeys" add column "first_cta_key" text;
alter table "lead_journeys" add column "first_seen_at" timestamp;
alter table "lead_journeys" add column "last_visit_id" integer;
alter table "lead_journeys" add column "last_campaign_id" integer;
alter table "lead_journeys" add column "last_page_id" integer;
alter table "lead_journeys" add column "last_utm_source" text;
alter table "lead_journeys" add column "last_utm_medium" text;
alter table "lead_journeys" add column "last_utm_campaign" text;
alter table "lead_journeys" add column "last_referrer" text;
alter table "lead_journeys" add column "last_cta_key" text;
alter table "lead_journeys" add column "last_seen_at" timestamp;
alter table "lead_journeys" add column "attribution_model_version" text not null default 'journey_attribution_v1';

alter table "lead_journeys" add constraint "lead_journeys_first_visit_id_campaign_visits_id_fk" foreign key ("first_visit_id") references "public"."campaign_visits"("id") on delete set null on update no action;
alter table "lead_journeys" add constraint "lead_journeys_first_campaign_id_campaigns_id_fk" foreign key ("first_campaign_id") references "public"."campaigns"("id") on delete set null on update no action;
alter table "lead_journeys" add constraint "lead_journeys_first_page_id_campaign_pages_id_fk" foreign key ("first_page_id") references "public"."campaign_pages"("id") on delete set null on update no action;
alter table "lead_journeys" add constraint "lead_journeys_last_visit_id_campaign_visits_id_fk" foreign key ("last_visit_id") references "public"."campaign_visits"("id") on delete set null on update no action;
alter table "lead_journeys" add constraint "lead_journeys_last_campaign_id_campaigns_id_fk" foreign key ("last_campaign_id") references "public"."campaigns"("id") on delete set null on update no action;
alter table "lead_journeys" add constraint "lead_journeys_last_page_id_campaign_pages_id_fk" foreign key ("last_page_id") references "public"."campaign_pages"("id") on delete set null on update no action;
