-- Seed a curated intermediate prompt per audience+format
insert into prompts (name, purpose, audience, format, topic, model, system_prompt, user_prompt_template, metadata)
values
  ('IT Morning Keynote', 'intermediate', 'IT Companies', 'Morning Keynote', '', 'google/gemini-3.1-flash-lite-preview', 'Create a clear, confident intermediate content plan for an audience of IT leaders attending a Morning Keynote. Keep it premium, conversion-oriented, and organized into hero, benefits, and lead form.', 'Generate the intermediate landing-page content object for this request:\nAudience: {{audience}}\nFormat: {{format}}\n\n{{prompt}}', '{"seeded": true}'),
  ('IT Endnote', 'intermediate', 'IT Companies', 'Endnote', '', 'google/gemini-3.1-flash-lite-preview', 'Plan a concise endnote-focused landing page for IT Companies. Emphasize reflection, trust, and action in the hero, benefits, and lead form sections.', 'Generate the intermediate landing-page content object for this request:\nAudience: {{audience}}\nFormat: {{format}}\n\n{{prompt}}', '{"seeded": true}'),
  ('IT Business Breakfast', 'intermediate', 'IT Companies', 'Business Breakfast', '', 'google/gemini-3.1-flash-lite-preview', 'Construct a warm, opportunity-driven plan tailored to IT leaders at a Business Breakfast. Keep the messaging professional yet inviting.', 'Generate the intermediate landing-page content object for this request:\nAudience: {{audience}}\nFormat: {{format}}\n\n{{prompt}}', '{"seeded": true}'),
  ('IT Panel Moderation', 'intermediate', 'IT Companies', 'Panel Moderation', '', 'google/gemini-3.1-flash-lite-preview', 'Map out a structured landing page that positions the moderator as the trusted guide for a high-tech panel. Keep benefits grounded and the CTA confident.', 'Generate the intermediate landing-page content object for this request:\nAudience: {{audience}}\nFormat: {{format}}\n\n{{prompt}}', '{"seeded": true}'),
  ('IT Dinner Speech', 'intermediate', 'IT Companies', 'Dinner Speech', '', 'google/gemini-3.1-flash-lite-preview', 'Draft a dinner speech page plan for IT executives that feels intimate, strategic, and action-focused across hero, benefits, and lead form.', 'Generate the intermediate landing-page content object for this request:\nAudience: {{audience}}\nFormat: {{format}}\n\n{{prompt}}', '{"seeded": true}'),
  ('Banks Morning Keynote', 'intermediate', 'Banks', 'Morning Keynote', '', 'google/gemini-3.1-flash-lite-preview', 'Draft a results-oriented morning keynote plan for banking leaders, leaning into stability, data, and premium positioning.', 'Generate the intermediate landing-page content object for this request:\nAudience: {{audience}}\nFormat: {{format}}\n\n{{prompt}}', '{"seeded": true}'),
  ('Banks Endnote', 'intermediate', 'Banks', 'Endnote', '', 'google/gemini-3.1-flash-lite-preview', 'Compose a confident endnote strategy for bankers that acknowledges risk management and outlines clear next steps.', 'Generate the intermediate landing-page content object for this request:\nAudience: {{audience}}\nFormat: {{format}}\n\n{{prompt}}', '{"seeded": true}'),
  ('Banks Business Breakfast', 'intermediate', 'Banks', 'Business Breakfast', '', 'google/gemini-3.1-flash-lite-preview', 'Plan a business breakfast page for banks that blends precision with hospitality—highlight value, credibility, and effortless engagement.', 'Generate the intermediate landing-page content object for this request:\nAudience: {{audience}}\nFormat: {{format}}\n\n{{prompt}}', '{"seeded": true}'),
  ('Banks Panel Moderation', 'intermediate', 'Banks', 'Panel Moderation', '', 'google/gemini-3.1-flash-lite-preview', 'Create a panel moderation-focused plan for banking conferences that balances authority with curiosity-driven dialogue.', 'Generate the intermediate landing-page content object for this request:\nAudience: {{audience}}\nFormat: {{format}}\n\n{{prompt}}', '{"seeded": true}'),
  ('Banks Dinner Speech', 'intermediate', 'Banks', 'Dinner Speech', '', 'google/gemini-3.1-flash-lite-preview', 'Develop a dinner speech plan for bankers that blends storytelling with clear outcomes and invites follow-up conversations.', 'Generate the intermediate landing-page content object for this request:\nAudience: {{audience}}\nFormat: {{format}}\n\n{{prompt}}', '{"seeded": true}'),
  ('Associations Morning Keynote', 'intermediate', 'Associations', 'Morning Keynote', '', 'google/gemini-3.1-flash-lite-preview', 'Sketch a morning keynote plan for associations that feels civic-minded and action-ready.', 'Generate the intermediate landing-page content object for this request:\nAudience: {{audience}}\nFormat: {{format}}\n\n{{prompt}}', '{"seeded": true}'),
  ('Associations Endnote', 'intermediate', 'Associations', 'Endnote', '', 'google/gemini-3.1-flash-lite-preview', 'Build an endnote landing page for associations focusing on shared impact and future momentum.', 'Generate the intermediate landing-page content object for this request:\nAudience: {{audience}}\nFormat: {{format}}\n\n{{prompt}}', '{"seeded": true}'),
  ('Associations Business Breakfast', 'intermediate', 'Associations', 'Business Breakfast', '', 'google/gemini-3.1-flash-lite-preview', 'Plan a warm breakfast narrative for association leaders that balances mission and measurable outcomes.', 'Generate the intermediate landing-page content object for this request:\nAudience: {{audience}}\nFormat: {{format}}\n\n{{prompt}}', '{"seeded": true}'),
  ('Associations Panel Moderation', 'intermediate', 'Associations', 'Panel Moderation', '', 'google/gemini-3.1-flash-lite-preview', 'Map a panel moderation page for associations that fosters inclusive dialogue and clear takeaways.', 'Generate the intermediate landing-page content object for this request:\nAudience: {{audience}}\nFormat: {{format}}\n\n{{prompt}}', '{"seeded": true}'),
  ('Associations Dinner Speech', 'intermediate', 'Associations', 'Dinner Speech', '', 'google/gemini-3.1-flash-lite-preview', 'Create a dinner speech blueprint for association gatherings that feels ceremonial yet modern.', 'Generate the intermediate landing-page content object for this request:\nAudience: {{audience}}\nFormat: {{format}}\n\n{{prompt}}', '{"seeded": true}')
on conflict do nothing;
