INSERT INTO public.media_assets (
  id,
  kind,
  title,
  description,
  usage_notes,
  avoid_notes,
  primary_url,
  thumbnail_url,
  thumbnail_alt,
  section_types,
  topics,
  audiences,
  formats,
  intent_tags,
  is_active,
  priority
) VALUES
(
  'hybrid-ai-clarity-abstract-v1',
  'image',
  'AI clarity abstract outcome artwork',
  'Semi-abstract editorial artwork representing complexity resolving into clarity, designed for audience outcome cards focused on practical understanding of AI in a business context.',
  'Use for hybrid content sections where the takeaway is understanding AI clearly, cutting through noise, or helping audiences make sense of emerging technology in practical terms. Best when messaging emphasizes clarity, comprehension, or strategic understanding.',
  'Avoid when the card is specifically about implementation steps, operational execution, or organizational change alignment, where a more action- or systems-oriented image is stronger.',
  'http://127.0.0.1:54321/storage/v1/object/public/campaign-assets/benefits/clarity.png',
  null,
  null,
  ARRAY['hybrid_content_section'],
  ARRAY['artificial intelligence','future of work','innovation','business transformation'],
  ARRAY['Corporate Leadership','IT Companies','Associations','Executive Teams'],
  ARRAY['Keynote','Workshop','Seminar','Conference'],
  ARRAY['clarity','understanding','practical insight','sensemaking'],
  true,
  70
),
(
  'hybrid-ai-alignment-abstract-v1',
  'image',
  'AI alignment abstract outcome artwork',
  'Semi-abstract editorial artwork representing multiple elements converging into a unified intelligent system, designed for audience outcome cards about alignment, collaboration, and readiness for change.',
  'Use for hybrid content sections where the takeaway is team alignment, future-of-work readiness, cross-functional understanding, or organizational confidence around AI-driven change. Best when messaging is about convergence, shared direction, or coordinated adaptation.',
  'Avoid when the card is primarily about first-principles AI understanding or immediate next-step execution, where clarity- or momentum-oriented visuals are more precise.',
  'http://127.0.0.1:54321/storage/v1/object/public/campaign-assets/benefits/alignment.png',
  null,
  null,
  ARRAY['hybrid_content_section'],
  ARRAY['artificial intelligence','future of work','organizational change','business transformation'],
  ARRAY['Corporate Leadership','HR Teams','Associations','Executive Teams'],
  ARRAY['Keynote','Workshop','Seminar','Conference'],
  ARRAY['alignment','change readiness','collaboration','shared direction'],
  true,
  71
),
(
  'hybrid-ai-momentum-abstract-v1',
  'image',
  'AI momentum abstract outcome artwork',
  'Semi-abstract editorial artwork representing structured forward motion and directional pathways, designed for audience outcome cards focused on actionable next steps and practical momentum after an AI keynote.',
  'Use for hybrid content sections where the takeaway is execution, implementation, action planning, or practical next steps after the session. Best when messaging emphasizes momentum, application, or moving from insight into action.',
  'Avoid when the card is mainly about understanding core concepts or building team-wide alignment, where the clarity or alignment variants are more suitable.',
  'http://127.0.0.1:54321/storage/v1/object/public/campaign-assets/benefits/momentum.png',
  null,
  null,
  ARRAY['hybrid_content_section'],
  ARRAY['artificial intelligence','innovation','implementation','business transformation'],
  ARRAY['Corporate Leadership','IT Companies','Associations','Operations Teams'],
  ARRAY['Keynote','Workshop','Seminar','Conference'],
  ARRAY['action','implementation','momentum','next steps'],
  true,
  72
);